import type { Registry } from './types';
import type { ResolvedStack } from './resolve-stack';

/** THIRD_PARTY_NOTICES text for exactly the providers a build ships — generated, never hand-edited. */
export function buildNotices(registry: Registry, stack: ResolvedStack): string {
  const lines = ['# Map data and imagery providers (generated by @masterchillax/globe-kit)', '', `Registry ${registry.version} · updated ${registry.updated} · record ${registry.record}`, ''];
  for (const id of stack.included) {
    const p = registry.providers.find((x) => x.id === id);
    if (!p) continue;
    lines.push(`## ${p.id}`, `- attribution: ${p.attribution}`, `- licence: ${p.license.name}`, `- url: ${p.license.url}`, `- verified: ${p.license.verified}`);
    if (p.license.note) lines.push(`- note: ${p.license.note}`);
    lines.push('');
  }
  if (stack.dropped.length) {
    lines.push('## Not shipped in this build', ...stack.dropped.map((d) => `- ${d.id}: ${d.reason}`), '');
  }
  return lines.join('\n');
}
